### PR TITLE
Process GameAssembly.dll and global.metadata.dll from runtime

### PR DESCRIPTION
**Pull request by krulci**
## Description
Implemented `Il2CppDumper version 6.7.40`
Implemented `PrincessDumper`
Added Public `IL2CPPInteropAssemblyPath` For `XUnity.AutoTranslator`.
Added `UseApplicationDataPath`.

## Motivation and Context
`PrincessDumper` will retrieve `GameAssembly.dll` from current process handle.
`PrincessDumper` will fix all sections so it can be processed by `Il2CppDumper`.
`PrincessDumper` will also extract `global-metadata.dat` from current process handle.
This feature is for games with `global-metadata.dat` embedded in `GameAssembly.dll`.
Applied `CheckIfGenerationRequired()` before `PrincessDumper`'s execution.
Uses `Il2CppDumper` to process `List<Mono.Cecil.AssemblyDefinition>` since `Cpp2IL` is incompetent with memory dumped file.
`IL2CPPInteropAssemblyPath` was added for XUnity.AutoTranslator. (Plan to migrate`XUnity.AutoTranslator` from `Unhollower` to `Il2CppInterop`.)
`UseApplicationDataPath` was added to reduce the need of initilization toolchain rerun for environment where `BepInEx` is removed upon exit.

## How Has This Been Tested?
Tested with PrincessConnectReDive (JP)
`Chainloader startup complete`
Tested with Umamusume (JP)
```
[Error  :InteropManager] Failed to generate Il2Cpp interop assemblies: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppInterop.Generator.Passes.Pass80UnstripMethods.GetOrCreateProperty(MethodDefinition unityMethod, MethodDefinition newMethod) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Passes/Pass80UnstripMethods.cs:line 132
   at Il2CppInterop.Generator.Passes.Pass80UnstripMethods.DoPass(RewriteGlobalContext context) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Passes/Pass80UnstripMethods.cs:line 110
   at Il2CppInterop.Generator.Runners.InteropAssemblyGeneratorRunner.Run(GeneratorOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Runners/InteropAssemblyGenerator.cs:line 173
   at Il2CppInterop.Generator.Il2CppInteropGenerator.Start() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Il2CppInteropGenerator.cs:line 30
   at Il2CppInterop.Generator.Il2CppInteropGenerator.Run() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Generator/Il2CppInteropGenerator.cs:line 47
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.RunIl2CppInteropGenerator(List`1 sourceAssemblies) in C:\Users\_\source\repos\BepInEx\Runtimes\Unity\BepInEx.Unity.IL2CPP\Il2CppInteropManager.cs:line 429
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.GenerateInteropAssembliesFromIl2CppDumper(List`1 cecilAssemblies) in C:\Users\_\source\repos\BepInEx\Runtimes\Unity\BepInEx.Unity.IL2CPP\Il2CppInteropManager.cs:line 322
```
Umamusume (JP) will result at this error, but can be fixed with my `Il2CppInterop`'s pull request [Implemented TypeComparer For GetOrCreateProperty When There Are More … #91](https://github.com/BepInEx/Il2CppInterop/pull/91)

## Screenshots (if appropriate):
image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by ManlyMarco — COMMENTED** [review]
The fix looks fine to me but adding two submodules seems excessive, especially PrincessDumper since it's basically a single class. Someone actively working with the 6.x branch will have to chime in on the rest since I'm not familiar with the IL2Cpp part.

**Comment by KAPTOHKA** [comment]
I am not a programmer, I can only use and configure the software a little...
On the latest versions, [including this one](https://github.com/Kevga/XUnity.AutoTranslator/releases), I get stuck on this:
```c#
[Message: Preloader] BepInEx 6.0.0-be.672 - GAME
[Message: Preloader] Built from commit 472e950179f4a5ab2e4a89f26dba793795fb6811
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2021.3.25f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [XUnity Auto Translator 5.2.0]
[Error  :   BepInEx] Error loading [XUnity Auto Translator 5.2.0]: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'System.String BepInEx.Unity.IL2CPP.Preloader.get_IL2CPPInteropAssemblyPath()'.
   at XUnity.AutoTranslator.Plugin.BepInEx.AutoTranslatorPlugin..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 129
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411
[Info   :   BepInEx] Loading [XUnity Resource Redirector 2.0.0]
[Message:   BepInEx] Chainloader startup complete
```

**Comment by krulci** [comment]
> I am not a programmer, I can only use and configure the software a little...
> 
> On the latest versions, [including this one](https://github.com/Kevga/XUnity.AutoTranslator/releases), I get stuck on this:
> 
> ```c#
> 
> [Message: Preloader] BepInEx 6.0.0-be.672 - GAME
> 
> [Message: Preloader] Built from commit 472e950179f4a5ab2e4a89f26dba793795fb6811
> 
> [Info   :   BepInEx] System platform: Windows 10 64-bit
> 
> [Info   :   BepInEx] Process bitness: 64-bit (x64)
> 
> [Info   :   BepInEx] Running under Unity 2021.3.25f1
> 
> [Info   :   BepInEx] Runtime version: 6.0.7
> 
> [Info   :   BepInEx] Runtime information: .NET 6.0.7
> 
> [Info   : Preloader] 0 patcher plugins loaded
> 
> [Info   : Preloader] 0 assemblies discovered
> 
> [Message:AssemblyPatcher] Executing 0 patch(es)
> 
> [Message:   BepInEx] Chainloader initialized
> 
> [Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
> 
> [Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
> 
> [Info   :   BepInEx] 2 plugins to load
> 
> [Info   :   BepInEx] Loading [XUnity Auto Translator 5.2.0]
> 
> [Error  :   BepInEx] Error loading [XUnity Auto Translator 5.2.0]: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
> 
>  ---> System.MissingMethodException: Method not found: 'System.String BepInEx.Unity.IL2CPP.Preloader.get_IL2CPPInteropAssemblyPath()'.
> 
>    at XUnity.AutoTranslator.Plugin.BepInEx.AutoTranslatorPlugin..ctor()
> 
>    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
> 
>    --- End of inner exception stack trace ---
> 
>    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
> 
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
> 
>    at System.Activator.CreateInstance(Type type)
> 
>    at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 129
> 
>    at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411
> 
> [Info   :   BepInEx] Loading [XUnity Resource Redirector 2.0.0]
> 
> [Message:   BepInEx] Chainloader startup complete
> 
> ``` 
You are not using the correct build.
That branch of XUAT requires this specific branch of BepInEx.
6.7.2 has not merged this branch so is not going to work.

**Comment by KAPTOHKA** [comment]
> You are not using the correct build.
> That branch of XUAT requires this specific branch of BepInEx.
> 6.7.2 has not merged this branch so is not going to work.

Ok...
I tried several previous versions, but the result is the same...
Tell me which version to use?

**Comment by krulci** [comment]
> > You are not using the correct build.
> 
> > That branch of XUAT requires this specific branch of BepInEx.
> 
> > 6.7.2 has not merged this branch so is not going to work.
> 
> 
> 
> Ok...
> 
> I tried several previous versions, but the result is the same...
> 
> Tell me which version to use?

You need to compile this branch.
This is one of the reason this pull request is submitted.

**Comment by KAPTOHKA** [comment]
> You need to compile this branch.
> This is one of the reason this pull request is submitted.

I don't compile(((
Gives a lot of errors including _Il2CppDumper_  &  _PrincessDumper_...
Or I'm doing something wrong...

**Comment by KAPTOHKA** [comment]
> You need to compile this branch.
> This is one of the reason this pull request is submitted.

Compiled your branch...
Used [THIS](https://github.com/Kevga/XUnity.AutoTranslator/releases) Auto-Translator and now everything works...)))
It doesn't work with the original Auto-Translator...
Thank you...

**Pull request closed without merging**
